name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: write-all

jobs:
  pr-pipeline:
    name: 'PR-pipeline'
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v5
      - name: ğŸ  Setup Node
        uses: actions/setup-node@v5
        with:
          always-auth: 'true'
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: âš™ï¸ Install Dependencies
        run: npm ci
      - name: ğŸ§¬ Lint
        run: npm run lint
      - name: ğŸ’â€â™€ï¸ Prettier
        run: npm run prettier
      - name: ğŸ” Typecheck
        run: npm run typecheck
      - name: ğŸ‘·ğŸ½ Build Package
        run: npm run build
